version: '3'
services:
  samba:
    build: .
    ports:
      - "135:135"
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    volumes:
      - persist-share:/samba/public

volumes: 
  persist-share: